openapi: 3.0.3
info:
  title: Coupon API
  description: 优惠券相关API接口
  version: 1.0.0

paths:
  /marketing/coupons:
    get:
      summary: 获取优惠券列表
      description: 获取可领取的优惠券列表（首页限时优惠区域）
      operationId: getCoupons
      tags:
        - Coupon
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: 成功获取优惠券列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          $ref: '#/components/schemas/Coupon'
                      total:
                        type: integer
                      page:
                        type: integer
                      page_size:
                        type: integer
        '401':
          description: 未授权

  /marketing/coupons/{id}:
    get:
      summary: 获取优惠券详情
      description: 获取指定优惠券详情
      operationId: getCouponDetail
      tags:
        - Coupon
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 优惠券ID
          schema:
            type: integer
      responses:
        '200':
          description: 成功获取优惠券详情
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Coupon'
        '401':
          description: 未授权
        '404':
          description: 优惠券不存在

  /marketing/coupons/{id}/receive:
    post:
      summary: 领取优惠券
      description: 用户领取指定优惠券
      operationId: receiveCoupon
      tags:
        - Coupon
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 优惠券ID
          schema:
            type: integer
      responses:
        '200':
          description: 领取成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: 领取成功
                  data:
                    type: object
                    properties:
                      user_coupon_id:
                        type: integer
                        description: 用户优惠券记录ID
                      expired_at:
                        type: string
                        format: date-time
                        description: 过期时间
        '400':
          description: 领取失败（已领取/已抢光/已过期）
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 优惠券已抢光
        '401':
          description: 未授权
        '404':
          description: 优惠券不存在

  /marketing/user-coupons:
    get:
      summary: 获取我的优惠券
      description: 获取当前用户已领取的优惠券列表
      operationId: getUserCoupons
      tags:
        - UserCoupon
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          description: 优惠券状态
          required: false
          schema:
            type: integer
            enum: [0, 1, 2]
            description: 状态 (0=未使用, 1=已使用, 2=已过期)
        - name: page
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: 成功获取我的优惠券
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          $ref: '#/components/schemas/UserCoupon'
                      total:
                        type: integer
                      page:
                        type: integer
                      page_size:
                        type: integer
        '401':
          description: 未授权

  /marketing/user-coupons/available:
    get:
      summary: 获取可用优惠券
      description: 获取当前用户可用的优惠券列表
      operationId: getAvailableUserCoupons
      tags:
        - UserCoupon
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 成功获取可用优惠券
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          $ref: '#/components/schemas/UserCoupon'
                      total:
                        type: integer
                      page:
                        type: integer
                      page_size:
                        type: integer
        '401':
          description: 未授权

  /marketing/user-coupons/count:
    get:
      summary: 获取各状态优惠券数量
      description: 获取当前用户各状态优惠券数量统计
      operationId: getCouponCountByStatus
      tags:
        - UserCoupon
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功获取数量统计
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    additionalProperties:
                      type: integer
                    example:
                      unused: 5
                      used: 3
                      expired: 2
        '401':
          description: 未授权

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Coupon:
      type: object
      required:
        - id
        - name
        - type
        - value
        - min_amount
        - start_time
        - end_time
        - total_count
        - received_count
        - per_user_limit
        - status
      properties:
        id:
          type: integer
          description: 优惠券ID
          example: 3001
        name:
          type: string
          description: 优惠券名称
          maxLength: 100
          example: 满100减20优惠券
        type:
          type: string
          description: 优惠券类型
          enum: [fixed, percent]
          example: fixed
        value:
          type: number
          description: 面额/折扣值 (fixed类型为面额，percent类型为折扣率如0.1表示9折)
          minimum: 0
          example: 20.00
        min_amount:
          type: number
          description: 使用门槛(最低消费金额)
          minimum: 0
          example: 100.00
        max_discount:
          type: number
          description: 最大优惠金额(仅percent类型有效)
          nullable: true
        applicable_scope:
          type: string
          description: 适用范围
          enum: [all, category, product, rental, mall, hotel]
          example: all
        start_time:
          type: string
          format: date-time
          description: 开始时间
          example: 2026-01-17T00:00:00Z
        end_time:
          type: string
          format: date-time
          description: 结束时间
          example: 2026-02-17T23:59:59Z
        total_count:
          type: integer
          description: 总发行量
          minimum: 1
          example: 1000
        received_count:
          type: integer
          description: 已领取数量
          minimum: 0
          example: 523
        remain_count:
          type: integer
          description: 剩余数量
          minimum: 0
          example: 477
        per_user_limit:
          type: integer
          description: 每人限领数量
          minimum: 1
          example: 1
        description:
          type: string
          description: 优惠券描述
          nullable: true
        status:
          type: integer
          description: 状态 (0=下架, 1=上架)
          enum: [0, 1]
        can_receive:
          type: boolean
          description: 当前用户是否可领取
          example: true
        received_by_user:
          type: integer
          description: 当前用户已领取数量
          example: 0

    UserCoupon:
      type: object
      required:
        - id
        - user_id
        - coupon_id
        - status
        - expired_at
        - received_at
      properties:
        id:
          type: integer
          description: 用户优惠券记录ID
        user_id:
          type: integer
          description: 用户ID
        coupon_id:
          type: integer
          description: 优惠券ID
        coupon:
          $ref: '#/components/schemas/Coupon'
          description: 优惠券详情
        order_id:
          type: integer
          description: 使用的订单ID
          nullable: true
        status:
          type: integer
          description: 状态 (0=未使用, 1=已使用, 2=已过期)
          enum: [0, 1, 2]
        expired_at:
          type: string
          format: date-time
          description: 过期时间
        used_at:
          type: string
          format: date-time
          description: 使用时间
          nullable: true
        received_at:
          type: string
          format: date-time
          description: 领取时间
