openapi: 3.0.3
info:
  title: Product API
  description: 商城商品相关API接口
  version: 1.0.0

paths:
  /categories:
    get:
      summary: 获取商品分类列表
      description: 获取商城所有商品分类
      operationId: getCategories
      tags:
        - Category
      responses:
        '200':
          description: 成功获取分类列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'

  /products:
    get:
      summary: 获取商品列表
      description: 支持分类筛选、排序、分页
      operationId: getProducts
      tags:
        - Product
      parameters:
        - name: category_id
          in: query
          description: 分类ID
          required: false
          schema:
            type: integer
        - name: sort_by
          in: query
          description: 排序方式
          required: false
          schema:
            type: string
            enum: [default, sales, price_asc, price_desc, new]
            default: default
        - name: page
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: 成功获取商品列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'

  /products/selected:
    get:
      summary: 获取精选商品
      description: 获取首页精选商品列表
      operationId: getSelectedProducts
      tags:
        - Product
      parameters:
        - name: limit
          in: query
          description: 返回数量限制
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 20
            default: 6
      responses:
        '200':
          description: 成功获取精选商品
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

  /products/hot:
    get:
      summary: 获取热门商品
      description: 获取销量最高的热门商品
      operationId: getHotProducts
      tags:
        - Product
      parameters:
        - name: limit
          in: query
          description: 返回数量限制
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 成功获取热门商品
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

  /products/search:
    get:
      summary: 搜索商品
      description: 根据关键词搜索商品
      operationId: searchProducts
      tags:
        - Product
      parameters:
        - name: keyword
          in: query
          description: 搜索关键词
          required: true
          schema:
            type: string
            minLength: 1
        - name: page
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 成功获取搜索结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'

  /products/{id}:
    get:
      summary: 获取商品详情
      operationId: getProductDetail
      tags:
        - Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功获取商品详情
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/ProductDetail'
        '404':
          description: 商品不存在

components:
  schemas:
    Category:
      type: object
      required:
        - id
        - name
        - level
      properties:
        id:
          type: integer
          description: 分类ID
        name:
          type: string
          description: 分类名称
          maxLength: 50
        icon:
          type: string
          description: 图标标识
          nullable: true
        level:
          type: integer
          description: 分类层级
          minimum: 1
        parent_id:
          type: integer
          description: 父分类ID
          nullable: true
        children:
          type: array
          items:
            $ref: '#/components/schemas/Category'
          description: 子分类列表

    Product:
      type: object
      required:
        - id
        - name
        - images
        - price
        - category_id
        - sales
        - stock
        - unit
        - is_on_sale
      properties:
        id:
          type: integer
          description: 商品ID
        category_id:
          type: integer
          description: 分类ID
        category_name:
          type: string
          description: 分类名称 (详情接口返回)
        name:
          type: string
          description: 商品名称
          maxLength: 100
        subtitle:
          type: string
          description: 副标题
        images:
          type: array
          items:
            type: string
            format: uri
          description: 商品图片
          minItems: 1
        description:
          type: string
          description: 商品描述
        price:
          type: number
          description: 现价
          minimum: 0
        original_price:
          type: number
          description: 原价（划线价）
          minimum: 0
        stock:
          type: integer
          description: 库存
          minimum: 0
        sales:
          type: integer
          description: 销量
          minimum: 0
        unit:
          type: string
          description: 单位
        is_on_sale:
          type: boolean
          description: 是否在售
        is_new:
          type: boolean
          description: 是否新品
        is_hot:
          type: boolean
          description: 是否热销

    ProductDetail:
      allOf:
        - $ref: '#/components/schemas/Product'
        - type: object
          properties:
            skus:
              type: array
              items:
                $ref: '#/components/schemas/ProductSku'
              description: SKU列表

    ProductSku:
      type: object
      required:
        - id
        - sku_code
        - price
        - stock
      properties:
        id:
          type: integer
          description: SKU ID
        sku_code:
          type: string
          description: SKU编码
        attributes:
          type: object
          additionalProperties:
            type: string
          description: SKU属性键值对 (如 {"颜色": "红色", "尺寸": "L"})
        price:
          type: number
          description: SKU价格
          minimum: 0
        stock:
          type: integer
          description: SKU库存
          minimum: 0
        image:
          type: string
          format: uri
          description: SKU图片

    ProductListResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/Product'
            total:
              type: integer
            page:
              type: integer
            page_size:
              type: integer
            total_pages:
              type: integer
